### ISSUE TITLE
Captions Stop without being pause

### ISSUE THREAD

**Issue by hrisgirl** [jptrsn/zip-captions#68] opened 2023-09-24 18:02 UTC
While running captions via a Google Chrome session, captions were paused 6 times during the church sermon without any action on our side. We were using the Share functionality and the first time this happened, we lost connection to the tablets viewing our session. The remaining times it auto paused we had to start the captions back.

**Comment by jptrsn** [comment] 2023-09-25 13:38
I'm unclear what you mean by "captions were paused 6 times" - did the pause notification appear on the host or client devices? Or did the captioning simply halt without indicating any errors? Or was it something different?

**Comment by crippit** [comment] 2023-09-25 23:42
Chrome has started to run 'Power Saving Mode', you can tell Chrome not to limit the power that it uses for ZipCaptions by adding it to the exceptions list. This is similar to the known issue addressed by the article kb1 https://help.zipcaptions.app/knowledge_base/kb_1.html

**Comment by hrisgirl** [comment] 2023-09-30 22:32
Let me start by clarifying that these issues happened while using the Sharing feature on Sunday. Since we are a church, we start the service with captions, pause the captions during the music portion of the service then start the captions back once music is over and the prayer and sermon starts. It was our experience that during the sermon, which is the longest time period we constantly run captions, the captions were stopped without my pausing them. It was as if I had paused or stopped the session. 
 
I have tested this multiple times (with a playback of the sermon) and the captions stop exactly at 5 minutes. I verified if memory saver was on in Chrome and it was not however I did add https://zipcaptions.app to the Chrome Performance Settings exceptions to keep the app from going into Memory Saving Mode but there was no change in results. In more than one instance, when the captions stopped, I lost the arrow option at the right of the screen to start the captions back. In these cases, I had to restart a new sharing session and connect the tablet to the new session (see screen shot 1).  With all the other instances, after captions stop, I have to click on the Pause button in order to receive the 'Recognition has been paused...' notification and then start captions back (see screen shot 2).
 
As a final test, I ran captions from the home page of ZipCaptions without using the Sharing feature but had the same result. Captions stop exactly at 5 minutes every time.
 
Is there something I am missing?
 
Thanks!
 
Renee Babineau
Wonder Lake Bible Church Media Director

**Comment by crippit** [comment] 2023-09-30 22:57
As a final test here, can you install the PWA version? You can find it by clicking on the three dots and then install. 

Can you please let us know:

- Which version of Chrome
- Your OS and version
- If you have tried in a new incognito tab

**Comment by hrisgirl** [comment] 2023-10-01 00:37
I have run it from the installed version with the same result. I am using a windows 10 computer on chrome version 117.0.5938.132 official build 64-bit.I have not tried incognito but will do so in the morning when I am back at the church doing my prep work for service. Thanks! Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Chris Webb ***@***.***> Date: 9/30/23  5:57 PM  (GMT-06:00) To: jptrsn/zip-captions ***@***.***> Cc: hrisgirl ***@***.***>, Author ***@***.***> Subject: Re: [jptrsn/zip-captions] Captions Stop without being pause (Issue
  #68) 
As a final test here, can you install the PWA version? You can find it by clicking on the three dots and then install.
Can you please let us know:

Which version of Chrome
Your OS and version
If you have tried in a new incognito tab

**Comment by hrisgirl** [comment] 2023-10-01 13:20
Good Morning.
 
As promised, I ran the same test in an incognito tab. This time the captions stopped around 2 minutes. I also ran the same test on my home computer which is an HP Windows 11 system and it also stopped at 5 minutes. If you would like to run the same test, I was playing the most recent podcast posted to our website (http://www.wlbiblechurch.org). 
 
Being a church, we have a lot of balls in the air at the same time during service so having to move away from our presentation program to restart captions is problematic with everything to run smoothly, especially when I have volunteers running the main computer. Because of this, I will hold off using ZC for today's service and utilize our legacy system since it will not be sunsetting until the end of this month.
 
I look forward working with you to help resolve this issue. I believe ZC is the right solution for us and have confidence that we can get this to work.
 
Thank you!
 
Renee Babineau
Wonder Lake Bible Church Media Director

**Comment by crippit** [comment] 2023-10-01 19:46
Ok, so I've run some tests of my own.

Firstly can you try with some sort of external microphone? This could be a wired headset with a mic, or a dedicated external microphone. 

Secondly in Chrome, can you please open ZipCaptions and then run the captions as usual, then go to the three dots > more tools > developer tools (or press Ctrl+Shift+I), in the sidebar that opens, can you click on Console at the top (it's a tab) and see if any errors (red or yellow) appear when the captioning stops?

Thanks!

**Comment by hrisgirl** [comment] 2023-10-03 03:22
Thank you Chris.I will be up at church tomorrow night doing some maintenance and I will run those additional tests then. Just to clarify, when the initial problem surface during service on 9/24, the microphone input was coming from a USB connection from the sound board directly into the computer. My test following that service were of the playback of that service. When I am the church tomorrow, I will use a microphone and will bring a USB headset with a microphone to test the different inputs. I will follow up with my findings. Thank you! Renée Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Chris Webb ***@***.***> Date: 10/1/23  2:46 PM  (GMT-06:00) To: jptrsn/zip-captions ***@***.***> Cc: hrisgirl ***@***.***>, Author ***@***.***> Subject: Re: [jptrsn/zip-captions] Captions Stop without being pause (Issue
  #68) 
Ok, so I've run some tests of my own.
Firstly can you try with some sort of external microphone? This could be a wired headset with a mic, or a dedicated external microphone.
Secondly in Chrome, can you please open ZipCaptions and then run the captions as usual, then go to the three dots > more tools > developer tools (or press Ctrl+Shift+I), in the sidebar that opens, can you click on Console at the top (it's a tab) and see if any errors (red or yellow) appear when the captioning stops?
Thanks!

**Comment by crippit** [comment] 2023-10-03 10:32
Ah ha! Your issue I suspect is the USB device. Chrome can be very fussy with USB audio devices. 

Let me know how you get on with trying different input sources.

**Comment by hrisgirl** [comment] 2023-10-03 13:29
Chris,
 
I ran a preliminary test this morning from home laptop using my USB headset and reading my son's Science Safety Contract. At the same time I had the stop watch on my phone running and again at 5 minutes, captions stopped. With this instance (my first test of the day) I also lost the arrow at the right where I could pause/restart captions.  
 
Per your instructions, I opened the developer tools and there was an error (screen shot attached). I will do a similar test on the church computer tonight as well.
 
Thank you!
Renee

**Comment by hrisgirl** [comment] 2023-10-03 22:49
Chris,
 
I had some maintenance to do to the sanctuary computer so I decided to replace the USB cable to the Alesis Mixer which feeds the service audio into the computer for live streaming, podcast recording and audio from the computer to the sound board for service. 
 
Prior to testing the input from the soundboard to ZC, I plugged in a USB microphone started captions on a Chrome session and read the same Safety text I read this morning from my home computer. The result was the same...captions stopped at 5 minutes. The USB microphone was plugged into a different USB port to rule out an issue with the port. I then pulled up the console and saw an error (see print screen attached). As you will see on the screen shot, I lost the ability to pause and restart the captions (just like this morning). The arrow is simply gone (fyi - the screen does a little flash when captions stop AND the arrow is removed). 
 
I ran the same test from the ZC app with the same results. I then opened the session in Chrome and grabbed the screen shot of the error. I did not run any further tests.
 
I hope this helps.
 
Renee.

**Comment by crippit** [comment] 2023-10-03 23:05
GitHub doesn't support screenshots by email.

You could join our discord or copy the console text here.

**Comment by hrisgirl** [comment] 2023-10-04 00:06
I'm not certain how much to copy/paste (I'm not a programmer) so I copy/paste the text I can.

SpeechRecognitionErrorEventisTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: SpeechRecognition__zone_symbol__endfalse: Array(1)0: pcallback: L=> {…}length: 1name: ""arguments: (...)caller: (...)[[FunctionLocation]]: main.340779d97ffb5242.js:1[[Prototype]]: ƒ ()[[Scopes]]: Scopes[4]cancelFn: ƒ (s)capture: falsedata: {useG: true, taskData: null}eventName: "end"invoke: ƒ invokeTask(T,t,r)options: undefinedrunCount: 6scheduleFn: ƒ (s)source: "EventTarget.addEventListener:end"target: SpeechRecognition {__zone_symbol__resultfalse: Array(1), __zone_symbol__endfalse: Array(1), __zone_symbol__errorfalse: Array(1), grammars: SpeechGrammarList, lang: 'en', …}type: "eventTask"_state: "scheduled"_zone: M {_parent: M, _name: 'angular', _properties: {…}, _zoneDelegate: v}_zoneDelegates: [v]state: (...)zone: (...)[[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object__zone_symbol__errorfalse: [p]__zone_symbol__resultfalse: [p]continuous: truegrammars: SpeechGrammarList {length: 0}interimResults: truelang: "en"maxAlternatives: 1onaudioend: nullonaudiostart: nullonend: nullonerror: nullonnomatch: nullonresult: nullonsoundend: nullonsoundstart: nullonspeechend: nullonspeechstart: nullonstart: null[[Prototype]]: SpeechRecognitiondefaultPrevented: falseerror: "network"eventPhase: 0message: ""returnValue: truesrcElement: SpeechRecognition__zone_symbol__endfalse: [p]__zone_symbol__errorfalse: [p]__zone_symbol__resultfalse: [p]continuous: truegrammars: SpeechGrammarListlength: 0[[Prototype]]: SpeechGrammarListaddFromString: ƒ addFromString()addFromUri: ƒ addFromUri()item: ƒ item()length: (...)Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.toStringTag): "SpeechGrammarList"get length: ƒ length()[[Prototype]]: ObjectinterimResults: truelang: "en"maxAlternatives: 1onaudioend: nullonaudiostart: nullonend: nullonerror: nullonnomatch: nullonresult: nullonsoundend: nullonsoundstart: nullonspeechend: nullonspeechstart: nullonstart: null[[Prototype]]: SpeechRecognitiontarget: SpeechRecognition__zone_symbol__endfalse: [p]__zone_symbol__errorfalse: [p]__zone_symbol__resultfalse: [p]continuous: truegrammars: SpeechGrammarList {length: 0}interimResults: truelang: "en"maxAlternatives: 1onaudioend: nullonaudiostart: nullonend: nullonerror: nullonnomatch: nullonresult: nullonsoundend: nullonsoundstart: nullonspeechend: nullonspeechstart: nullonstart: null[[Prototype]]: SpeechRecognitiontimeStamp: 347615.7000000477type: "error"[[Prototype]]: SpeechRecognitionErrorEvent
(anonymous) @ main.340779d97ffb5242.js:1

**Comment by jptrsn** [comment] 2023-10-04 18:53
Okay, that's given me a bit to work with. It appears to be something related to network connectivity, where if the connection to the speech recognition server provided by Google is disrupted, Zip Captions cannot re-establish a connection. I will try to reproduce the problem myself.

**Comment by crippit** [comment] 2023-10-05 01:36
@hrisgirl you can also attach images here by dragging and dropping the file.

**Comment by hrisgirl** [comment] 2023-10-15 02:18
Here are the screen shots I took
![ZC App Sanctuary USB Mic](https://github.com/jptrsn/zip-captions/assets/143332895/cac2f9c6-635b-4bcf-afb0-d75a7a7bae00)
<img width="960" alt="ZC Developoper Tools error" src="https://github.com/jptrsn/zip-captions/assets/143332895/72c4f84f-5d42-487e-ab1d-5870c23b4f35">
![ZC Sanctuary USB Mic](https://github.com/jptrsn/zip-captions/assets/143332895/bb2ab1eb-b6cb-40f9-8b0f-68341bfdf888)
![ZC Screen Shot 1](https://github.com/jptrsn/zip-captions/assets/143332895/cf1dcdf2-ebc4-4dc1-9d0d-89eb55ce3db3)
![ZC Screen Shot 2](https://github.com/jptrsn/zip-captions/assets/143332895/5d663de0-ab6a-4b44-a6ed-3da78a99ca0c)
![ZC Screen Shot 3](https://github.com/jptrsn/zip-captions/assets/143332895/9889b849-90ce-460e-9fd9-6a10aaff07d8)

**Comment by jptrsn** [comment] 2023-10-15 16:22
Thanks for adding the screenshots, that's very helpful!

In the last screenshot, I can see the "Recognition has been paused" notification showing on screen. From your earlier description, I understand that this does not happen when the problem occurs - the screen just stops showing new results and you lose the blue sidebar of controls. Then, you need to click the button to "end broadcast" and then restart the broadcast for it to resume functionality.

Is this description accurate?

I have a good idea of the potential issue. However, it will be difficult to address, so I am not able to give you a timeline for when you can expect the bug to be fixed. It should be in the next couple weeks, time permitting, if my assumption about the nature of the problem is accurate.

For the time being, your best solution would be to just refresh the app/page (ctrl R on the keyboard), then click start broadcast. Most of the time, this will just resume the same broadcast as was started earlier. You can expect improvements to the broadcast experience coming in the next few weeks, in addition to my work on fixing this problem.

Thanks for your patience and communication as we work to address the problem. It really is extremely helpful to me, and your efforts will help a lot of other folks who may run into the same bug in the future, but they'll never know! :)

**Comment by hrisgirl** [comment] 2023-11-04 17:22
My apologies for the delayed response. I have been out ill. The captions stop at exactly 5 minutes regardless. Sometimes the 'Recognition has been paused' is displayed, sometimes not and other times we loose the menu arrow to manually pause captions. I have tried running additional test and found that refreshing the page does not lose the sharing session however the chrome session is not the active application during the service. Our presentation program (ProPresenter 7) has to be active so the pastor can forward his slides during the sermon. If captions stop, I have to click away from Pro7, refresh the chrome session then click back on Pro7. This hasn't always happened timely and has caused disruption in the slides. 

If it helps, The applications I have open on Sunday morning include Chrome (for captions), Audacity (to record the audio for our podcast), Pro7 (for the presentation) along with Companion and Dropbox running in the background.

**Comment by crippit** [comment] 2023-11-05 01:44
At this point this looks to be an issue with either your network, your specific device or the other applications that you are using. We have had no other reports of this issue. As one on one support is something that we offer for our Pateron supporters, we would invite you to join our discord server and to support us on Pateron. 

We will be closing this bug, as we cannot reproduce it to resolve it.

**Comment by hrisgirl** [comment] 2023-11-05 18:04
Thank you. We will be joining as a Pateron supporter this week. Once this issue is resolved for us, I'd love to talk about a dedicated sharing session ID.

**Comment by crippit** [comment] 2023-11-05 18:06
This will also be something which will roll out for our Patreon supporters,
we need to finish work on our backend first.

**Comment by hrisgirl** [comment] 2023-11-05 18:12
Perfect. Membership has been added under Wonder Lake Bible Church. Thank you!

**Comment by crippit** [comment] 2023-11-05 19:09
Fantastic. Feel free to join out discord server:
https://discord.com/invite/qEUunKCE and link it to your Pateron account.

**Comment by curtgrimes** [comment] 2023-12-31 02:31
For what it's worth, with Web Captioner I was experiencing the same issue described by OP -- caption text would seemingly stop coming back even though I was still hearing audio over the microphone and there were otherwise no issues with the internet connection. There would be no errors coming back from the API and I believe a [SpeechRecognition `end()` event](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/end_event) wouldn't fire. I saw the same thing happen on different networks/computers after several minutes. Doing a quick `SpeechRecognition.stop()` and `SpeechRecognition.start()` would resolve the issue at the expense of losing 1-2 words if there was speech coming in at that moment.

In Web Captioner I added logic for restarting captioning behind-the-scenes (invisible to the user) if we haven't gotten any caption data back after a while:
- In the original iteration of Web Captioner: https://github.com/curtgrimes/webcaptioner/commit/43baabbd7bc151478ef44d4a0f05e7f1004ad0cb and https://github.com/curtgrimes/webcaptioner/commit/efc258ebb85a0ad2d21373608b899d0890bb0e40
- Later on in the most recent rewrite, with some volume level checks added: https://github.com/curtgrimes/webcaptioner/commit/dd402a95ee75907856abe2911d092eae271430da#diff-a50c2eb9102deb26190f3332faf59f1ebd4f726fccfa7e2ee0cdc97b2378d474

These seem to describe the same issue:
- "The transcription prints for a while but stops after a certain time" https://stackoverflow.com/questions/77384609/is-there-is-a-time-limit-to-speech-recognition-while-using-web-speech-api
- https://github.com/bigbluebutton/bigbluebutton/issues/12782

Hope this helps -- I figured I would write some of this out while I still remember it.

**Comment by curtgrimes** [comment] 2023-12-31 03:10
Actually after looking at ZipCaptions, it seems like the auto-restart loop is something you already do, but does [this mean](https://github.com/jptrsn/zip-captions/blob/01f3bcc2638a28a432672b0e1115e16270d419ce/packages/client/src/app/modules/media/services/recognition.service.ts#L271) that a `start()` isn't happening again after the `stop()` inside that error handler? If so, are you open to a PR adding it? I'm trying to reproduce the issue first and see if the added `start()` actually fixes it, but unfortunately I haven't been successful yet. :/

**Comment by jptrsn** [comment] 2023-12-31 21:20
Hi Curt,

Thanks for looking into this. In fact, the problem needs to be solved in the broadcast functionality, as when there's a network interruption, it will not recover and resume the broadcast. We've been discussing it in the discord server, and the cause is a problem related to the network infrastructure.

At some point, I'll fix this issue, but for now, I'll need to get some new features out first, since the solution will actually involve relying on a new backend that uses a different approach to setting up broadcast sessions, hosts, peers, and so on.

Your proposed fix would potentially cause side-issues when there's a fatal error, as it would end up creating a recovery-loop that would likely lock up the UI. I can look at using a backoff with a max retry, which is my intent for the recovery logic (e.g. try 5 times, then give up) so that it will not end up crashing or sitting in an infinite loop.

Thanks again!

**Comment by iwt-jandwinger** [comment] 2024-01-08 12:49
it's confirmed, it's a network issue!
you can reproduce easily with vpn connect/disconnect  during translation


`SpeechRecognitionErrorEvent {isTrusted: true, error: 'network', message: '', type: 'error', target: SpeechRecognition, …}
isTrusted
: 
true
bubbles
: 
false
cancelBubble
: 
false
cancelable
: 
false
composed
: 
false
currentTarget
: 
SpeechRecognition {__zone_symbol__resultfalse: Array(1), __zone_symbol__endfalse: Array(1), __zone_symbol__errorfalse: Array(1), grammars: SpeechGrammarList, lang: 'en', …}
defaultPrevented
: 
false
error
: 
"network"
eventPhase
: 
0
message
: 
""
returnValue
: 
true
srcElement
: 
SpeechRecognition {__zone_symbol__resultfalse: Array(1), __zone_symbol__endfalse: Array(1), __zone_symbol__errorfalse: Array(1), grammars: SpeechGrammarList, lang: 'en', …}
target
: 
SpeechRecognition {__zone_symbol__resultfalse: Array(1), __zone_symbol__endfalse: Array(1), __zone_symbol__errorfalse: Array(1), grammars: SpeechGrammarList, lang: 'en', …}
timeStamp
: 
9798911.299999999
type
: 
"error"
[[Prototype]]
: 
SpeechRecognitionErrorEvent`

**Comment by hrisgirl** [comment] 2024-01-12 02:14
I'm glad you could replicate it however I am not connected via VPN but directly connected to my internal network. This does add to my believe that the issue is not necessarily with my network but the way that ZipCaptions interacts with networks. I am continuing to work with our provider to troubleshoot if there are errors on our side.

**Comment by jptrsn** [comment] 2024-01-12 02:29
There is indeed a problem with the Zip Captions app that needs to be addressed, and I have it on the roadmap to fix this problem. As I mentioned above,
> the problem needs to be solved in the broadcast functionality, as when there's a network interruption, it will not recover and resume the broadcast

This means that @hrisgirl your network does experience minor, brief, irregular disconnect/reconnect events, which the app _ought_ to be able to handle, but currently it does not. @iwt-jandwinger was offering additional information for troubleshooting purposes, using a vpn to reproduce a very brief period of network outage as the connection state changed.

I am keen to fix this problem, but it is currently down to a matter of both time and there being a new feature in development which will, when complete, fix the issue as it will change how the broadcast start/resume/terminate logic handles events, and a disconnect/reconnect will only result in viewers seeing a message showing "host offline" for the duration.

I will not close this issue, as the reported problem still exists and needs to be addressed, and this keeps a good channel open for me to keep you all updated on my progress, when I am able. However, I encourage anyone looking to post (aside from the reporter of this issue and myself) to read the thread in full, to avoid adding any confusion.

Apologies for the long delay, life has a way of taking up a lot of my time. I appreciate your patience and the help from everyone identifying the problem. I'll take care of it as soon as I'm able. 

Take care 
James :)

**Comment by jptrsn** [comment] 2024-02-12 14:34
We have released a bugfix that should help with intermittent issues such as this one. While it's not a full solution - that is, the app will not fully self-recover a broadcast if the network is too unstable - it should help reduce how many times you're seeing this problem. I'm fairly confident it should handle the scenario as I understand it, but it may not fully address the problem.

If the problem re-appears, I encourage you to open a new issue, so we can track it separately.

Thank you so much for your patience, I really hope it improves your experience with Zip Captions.

**Closed by jptrsn** 2024-02-12 14:34 UTC
Labels: bug, Plane, on roadmap
